# Generated by Django 4.1.7 on 2023-03-11 23:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('published_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_favs', models.IntegerField(default=0)),
                ('published_time', models.DateTimeField(default=datetime.datetime.now)),
                ('difficulty', models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')])),
                ('meal', models.IntegerField(choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Dinner'), (3, 'Desserts'), (4, 'Snacks'), (5, 'Other')])),
                ('diet', models.IntegerField(choices=[(0, 'Vegan'), (1, 'Vegetarian'), (2, 'Gluten-Free'), (3, 'Halal'), (4, 'Kosher'), (5, 'None')])),
                ('cuisine', models.IntegerField(choices=[(0, 'African'), (1, 'Carribean'), (2, 'East Asian'), (3, 'European'), (4, 'French'), (5, 'Italian'), (6, 'Middle-Eastern'), (7, 'North American'), (8, 'Oceanic'), (9, 'Russian'), (10, 'Spanish'), (11, 'South American'), (12, 'South Asian'), (13, 'Other')])),
                ('cooking_time', models.DurationField()),
                ('prep_time', models.DurationField()),
                ('calculated_total_time', models.DurationField(default=datetime.timedelta(0))),
                ('calculated_cook_time', models.DurationField(default=datetime.timedelta(0))),
                ('calculated_prep_time', models.DurationField(default=datetime.timedelta(0))),
                ('total_time', models.DurationField(default=datetime.timedelta(0))),
                ('servings_num', models.IntegerField()),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_recipe', to='recipes.recipemodel')),
                ('user_id', models.ForeignKey(default=recipes.models.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_num', models.PositiveIntegerField(default=0)),
                ('cooking_time', models.DurationField()),
                ('prep_time', models.DurationField()),
                ('instructions', models.CharField(max_length=225)),
                ('recipe_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipemodel')),
            ],
        ),
        migrations.CreateModel(
            name='StepMediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, upload_to='step-media/')),
                ('step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='recipes.stepmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='review-media/')),
                ('interaction_id', models.ForeignKey(default=recipes.models.get_default_interaction_id, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='recipes.interactionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeMediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='recipe-media/')),
                ('recipe_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='recipes.recipemodel')),
            ],
        ),
        migrations.AddField(
            model_name='interactionmodel',
            name='recipe_id',
            field=models.ForeignKey(default=recipes.models.get_default_recipe_id, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='recipes.recipemodel'),
        ),
        migrations.AddField(
            model_name='interactionmodel',
            name='user_id',
            field=models.ForeignKey(default=recipes.models.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IngredientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='cups', max_length=20)),
                ('recipe_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipemodel')),
            ],
        ),
    ]
