# Generated by Django 4.1.7 on 2023-03-06 12:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InteractionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='recipemediamodel',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipemodel'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='based_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipemodel'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='cooking_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='prep_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='servings_num',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_num', models.PositiveIntegerField()),
                ('cooking_time', models.DurationField()),
                ('prep_time', models.DurationField()),
                ('instructions', models.CharField(max_length=225)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipemodel')),
            ],
        ),
        migrations.CreateModel(
            name='StepMediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='step-media/')),
                ('step_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_media', to='recipes.stepmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('published_time', models.DateTimeField(default=datetime.datetime.now)),
                ('interaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.interactionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewMediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='review-media/')),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.reviewmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredientmodel')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipemodel')),
            ],
        ),
        migrations.AddField(
            model_name='interactionmodel',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipes.recipemodel'),
        ),
        migrations.AddField(
            model_name='interactionmodel',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredientmodel',
            name='recipes',
            field=models.ManyToManyField(related_name='ingredients', to='recipes.recipemodel'),
        ),
    ]
