# Generated by Django 4.1.7 on 2023-03-06 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_ingredientmodel_interactionmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionmodel',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='recipes.recipemodel'),
        ),
        migrations.AlterField(
            model_name='quantitymodel',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_quantities', to='recipes.ingredientmodel'),
        ),
        migrations.AlterField(
            model_name='quantitymodel',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_quantities', to='recipes.recipemodel'),
        ),
        migrations.AlterField(
            model_name='recipemediamodel',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='recipes.recipemodel'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='based_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_recipe', to='recipes.recipemodel'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewmediamodel',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='recipes.reviewmodel'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='interaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='recipes.interactionmodel'),
        ),
        migrations.AlterField(
            model_name='stepmediamodel',
            name='step_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='recipes.stepmodel'),
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipemodel'),
        ),
    ]
