# Generated by Django 4.1.7 on 2023-03-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_interactionmodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='servings_num',
            field=models.IntegerField(),
        ),
    ]
