# Generated by Django 4.1.7 on 2023-03-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_reviewmodel_interaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='based_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_recipe', to='recipes.recipemodel'),
        ),
    ]
