# Generated by Django 4.1.7 on 2023-03-10 17:22

from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_stepmediamodel_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemediamodel',
            name='recipe_id',
            field=models.ForeignKey(blank=True, default=recipes.models.get_default_recipe_id, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='recipes.recipemodel'),
        ),
        migrations.AlterField(
            model_name='stepmediamodel',
            name='step_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='recipes.stepmodel'),
        ),
    ]
