# Generated by Django 4.1.7 on 2023-03-10 18:06

from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipemediamodel_recipe_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemediamodel',
            name='recipe_id',
            field=models.ForeignKey(default=recipes.models.get_default_recipe_id, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='recipes.recipemodel'),
        ),
        migrations.AlterField(
            model_name='stepmediamodel',
            name='step_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='recipes.stepmodel'),
            preserve_default=False,
        ),
    ]
