# Generated by Django 4.1.7 on 2023-03-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipemediamodel_recipe_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='meal',
            field=models.IntegerField(choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Desserts'), (3, 'Snacks'), (4, 'Other')]),
        ),
    ]
