# Generated by Django 4.1.7 on 2023-03-10 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_ingredientmodel_recipe_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientmodel',
            name='recipe_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipemodel'),
        ),
        migrations.AlterField(
            model_name='recipemediamodel',
            name='recipe_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='recipes.recipemodel'),
        ),
        migrations.AlterField(
            model_name='stepmodel',
            name='recipe_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipemodel'),
        ),
    ]
