# Generated by Django 4.1.7 on 2023-03-11 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_recipemediamodel_recipe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='total_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
