# Generated by Django 4.1.7 on 2023-03-11 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_recipemodel_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='calculated_cook_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='calculated_prep_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='calculated_total_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
