# Generated by Django 4.1.7 on 2023-03-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_recipemodel_calculated_cook_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepmodel',
            name='step_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
